### ISSUE TITLE
Sampling is not robust

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#117]
Sampling is not yet robust. See #115. This test occasionally fails:

https://github.com/byu-dml/metalearn/blob/baf86ac734416cd546c82967ccb0ef0c5cfb8e32/test/metalearn/metafeatures/test_metafeatures.py#L485

Here is my terminal output:
```
(env) $ python run_tests.py
....E..........
======================================================================
ERROR: test_sampling_shape_correctness (test.metalearn.metafeatures.test_metafeatures.MetafeaturesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../metalearn/test/metalearn/metafeatures/test_metafeatures.py", line 489, in test_sampling_shape_correctness
    self.dummy_features, self.dummy_target, sample_shape=sample_shape
  File ".../metalearn/metalearn/metafeatures/metafeatures.py", line 131, in compute
    self._compute_metafeatures(metafeature_ids, timer)
  File ".../metalearn/metalearn/metafeatures/metafeatures.py", line 261, in _compute_metafeatures
    value, time_value = self._retrieve_resource(metafeature_id)
  File ".../metalearn/metalearn/metafeatures/metafeatures.py", line 270, in _retrieve_resource
    resource_name
  File ".../metalearn/metalearn/metafeatures/metafeatures.py", line 314, in _retrieve_parameters
    value, time_value = self._retrieve_resource(parameter)
  File ".../metalearn/metalearn/metafeatures/metafeatures.py", line 270, in _retrieve_resource
    resource_name
  File ".../metalearn/metalearn/metafeatures/metafeatures.py", line 314, in _retrieve_parameters
    value, time_value = self._retrieve_resource(parameter)
  File ".../metalearn/metalearn/metafeatures/metafeatures.py", line 283, in _retrieve_resource
    results = eval(f)(*retrieved_parameters)
  File ".../metalearn/metalearn/metafeatures/metafeatures.py", line 391, in _sample_rows
    raise Exception(f"sample_shape {sample_shape} sampled rows {n_sampled_rows}")
Exception: sample_shape (7, 13) sampled rows 8

----------------------------------------------------------------------
Ran 15 tests in 10.764s

FAILED (errors=1)
(env) $ python run_tests.py
...............
----------------------------------------------------------------------
Ran 15 tests in 10.966s

OK
```

**Comment by bjschoenfeld** [comment]
This error occurs about 1 in 1000 tests.

**Comment by bjschoenfeld** [comment]
Stratified sampling is required for the landmarkers, so that in cross validation, each fold has at least one instance of each class.

This begs the question of testing correctness under sampling conditions and essentially doubles all the tests. More work.

Perhaps sampling should be left to the user. I don't think this is a highly used feature and there has already been much discussion on sampling which would lead to more work. #35 #41 #80 #102 .
