### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#126]
A D3M user sent me this message:

I am getting a 'No space left on device error' when running byu's metafeatures extractor on the LL0_acled dataset. Do you know the cause for it? Here is the stracktrace

```
2018-08-09 13:52:48,558:INFO:alphad3m-24:d3m_ta2_nyu.workflow.execute:Executing module b67794ed-e56a-4dc7-8b62-a303c598c858 (d3m d3m.primitives.byudml.metafeature_extraction.MetafeatureExtractor), inputs: inputs
Process ForkPoolWorker-1:1:
2018-08-09 13:54:52,595:ERROR:alphad3m-24:d3m_ta2_nyu.workflow.execute:Got exception running module b67794ed-e56a-4dc7-8b62-a303c598c858
Traceback (most recent call last):
 File "/usr/src/app/d3m_ta2_nyu/workflow/execute.py", line 196, in execute
   cache=cache(db, run, module),
 File "/usr/src/app/d3m_ta2_nyu/workflow/module_loader.py", line 156, in wrapper
   results = primitive.produce(**produce_args)
 File "/usr/local/lib/python3.6/dist-packages/byudml/metafeature_extraction/metafeature_extraction.py", line 206, in produce
   metadata = self._produce(inputs.metadata, copy.copy(inputs), timeout)
 File "/usr/local/lib/python3.6/dist-packages/byudml/metafeature_extraction/metafeature_extraction.py", line 247, in _produce
   metafeatures = Metafeatures().compute(data, target_series, column_types=column_types, metafeature_ids=metalearn_metafeatures_to_compute, seed=self.random_seed, timeout=timeout)
 File "/usr/local/lib/python3.6/dist-packages/metalearn/metafeatures/metafeatures.py", line 99, in compute
   timeout,
 File "/usr/local/lib/python3.6/dist-packages/metalearn/metafeatures/metafeatures.py", line 129, in _threadsafe_timeout_function
   raise self.error.get()
OSError: [Errno 28] No space left on device
```

**Comment by bjschoenfeld** [comment]
Even though the stack trace shows that an older version of metalearn is being used, I was able to reproduce the error using the current develop branch. Linear Discriminant Analysis is the memory offender. The dataset has text columns which get one-hot encoded, exploding the number of features to be larger than the number of instances (15k+ instances). According to [this paper](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.128.3315&rep=rep1&type=pdf) on page 1, the memory complexity is `O(mn +mt + nt)` where `m` is the number of instances, `n` is the number of features and `t = min(m,n)`. We are looking at `O(n^2)` memory. See #127
