### ISSUE TITLE
Timeout causes broken pipe warnings

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/metalearn#82]
When some metafeatures timeout, a broken pipe warning is raised. This is difficult to reproduce, we currently ignore the warning with the `signal` package. Will this have side-effects, like ignoring other warnings? We should revisit how we handle this warning, perhaps by catching it and printing it or writing it to a log file.

**Comment by bjschoenfeld** [comment]
I reproduced the broken pipe warning in the `test_timeout` test with 1 second timeout. I could reproduce it once more, but later attempts have failed. Here is a dump:

```
........Process ForkPoolWorker-20:1:
Process ForkPoolWorker-20:2:
0.9282417297363281
E
======================================================================
ERROR: test_timeout (test.metalearn.metafeatures.test_metafeatures.MetaFeaturesWithDataTestCase)
Tests Metafeatures().compute() with timeout set
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../test/metalearn/metafeatures/test_metafeatures.py", line 238, in test_timeout
    self._test_correctness(computed_mfs, known_mfs, test_name + f"_{timeout}")
  File ".../test/metalearn/metafeatures/test_metafeatures.py", line 81, in _test_correctness
    elif not np.isnan(known_value) and not np.isnan(computed_value):
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

----------------------------------------------------------------------
Ran 9 tests in 13.609s

FAILED (errors=1)
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File ".../env/lib/python3.6/site-packages/sklearn/externals/joblib/pool.py", line 386, in put
    return send(obj)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File ".../env/lib/python3.6/site-packages/sklearn/externals/joblib/pool.py", line 372, in send
    self._writer.send_bytes(buffer.getvalue())
  File ".../env/lib/python3.6/site-packages/sklearn/externals/joblib/pool.py", line 386, in put
    return send(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File ".../env/lib/python3.6/site-packages/sklearn/externals/joblib/pool.py", line 372, in send
    self._writer.send_bytes(buffer.getvalue())
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
BrokenPipeError: [Errno 32] Broken pipe
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File ".../env/lib/python3.6/site-packages/sklearn/externals/joblib/pool.py", line 386, in put
    return send(obj)
  File ".../env/lib/python3.6/site-packages/sklearn/externals/joblib/pool.py", line 372, in send
    self._writer.send_bytes(buffer.getvalue())
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File ".../env/lib/python3.6/site-packages/sklearn/externals/joblib/pool.py", line 386, in put
    return send(obj)
  File ".../env/lib/python3.6/site-packages/sklearn/externals/joblib/pool.py", line 372, in send
    self._writer.send_bytes(buffer.getvalue())
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by macetheace96** [comment]
there's another possibility I'm looking into about closing and flushing the queue that will hopefully get rid of the issue without masking any warnings

**Comment by bjschoenfeld** [comment]
Timeout is closely coupled with multiprocessing and is a difficult problem. Until there is a stronger need for an internal timeout function, we will discontinue attempting to implement it. The user has some control over time by changing which metafeatures they request.

**Comment by bjschoenfeld** [comment]
Timeout has been removed in #107.
